### ISSUE TITLE
Segfault on OSX Mavericks

### ISSUE THREAD

**Issue by tleyden** [jpr5/ngrep#2]
To reproduce:
- On OSX Mavericks, install ngrep via homebrew or from source
- Run `sudo ngrep -W byline -d lo0 port 4984`

It will segfault.

A user [said they would report the issue](https://github.com/Homebrew/homebrew/issues/27171#issuecomment-36681690), but it looks like it never happened, so I'm reporting it.

**Comment by edburns** [comment]
I just built from source on a Mac OS X Mavericks 10.9.5 and observe the following when running 

sudo ./ngrep -d lo0 port 8080
interface: lo0 (127.0.0.0/255.0.0.0)
pcap compile: no VLAN support for data link type 0

It does not segfault, but it doesn't work either.

**Comment by tleyden** [comment]
FWIW, I'm not running into the issue on OSX El Capitan and ngrep: V1.45, $Revision: 1.93 $
