### ISSUE TITLE
ngrep -W byline output is garbled

### ISSUE THREAD

**Issue by kenstir** [jpr5/ngrep#6]
ngrep-1.44 recompiled from source works fine.  Output from the ngrep distributed from the EPEL repo is garbled, as is the output of the ngrep recompiled from git master.

Environment: centos 7.2.1511

Command: ngrep -I ngrep_bug.pcap -W byline -t|head -n 4

Expected output (ngrep-1.44):

<pre>
input: ngrep_bug.pcap
#
U 2016/03/28 15:01:01.852997 10.5.3.33:5062 -> 10.5.3.39:5060
SIP/2.0 200 OK.
</pre>

Actual output:

<pre>
input: /home/kenstir/Downloads/ngrep_bug.pcap
filter: (ip)
#
? 2016/03/28 15:01:01.852997 @ч -> 
6760SIPpTag0933165;lr=on>.
</pre>

[ngrep_bug.zip](https://github.com/jpr5/ngrep/files/204501/ngrep_bug.zip)

**Comment by jpr5** [comment]
Hey @kenstir ,

Sorry for the tardy reply, and thanks so much for the bug report and helpful pcap file.  

I think the culprit may be [Linux cooked sockets](https://bugzilla.redhat.com/show_bug.cgi?id=1401152).  From that report, I was able to repro with `ngrep -d any '' udp`, FYI.   

I'm looking into it now.

**Comment by jpr5** [comment]
OK, I think I got it in ce64df46d on master.

It looks like there've been many reports of this, in different ways; it even looks like there's an outstanding pull request around loopback processing that also solves this at its core issue (can't be sure as it doesn't say so, but probably not an accident).  

I've run your pcap through and it shows fine.  Would you mind confirming for me, in your own environment?  

In any case, appreciate the report and the opportunity to make ngrep better.  

cheers,
--jordan

**Comment by kenstir** [comment]
That fix works for me, thanks very much indeed!
